In [22]:
import numpy as np
from scipy.optimize import linprog

import pandas as pd

## Simulation 1
max z = 8x1 + 5x2

- x1 + x2 <= 6
- 9x1 + 5x2 <= 45
- x1, x2 >= 0

https://www.youtube.com/watch?v=heCeCPu83c0&t=321s 

In [94]:
A = np.array([[1, 1], [9, 5], [-1, 0], [0, -1]])
b = np.array([6, 45, 0, 0])
c = np.array([-8, -5])

res = linprog(c, A_ub=A, b_ub=b, method='simplex')
res

     con: array([], dtype=float64)
     fun: -41.25
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([0.  , 0.  , 3.75, 2.25])
  status: 0
 success: True
       x: array([3.75, 2.25])

## Simulation 2
max z = 5x1 + 6x2


- 4x1 + 2x2 <= 8
- 3x1 + 4x2 <= 12
- x1,x2 >= 0

https://www.youtube.com/watch?v=DmzVCX1-ZhI

In [20]:
A = np.array([[4, 2], [3, 4], [-1, 0], [0, -1]])
b = np.array([8, 12, 0, 0])
c = np.array([-5, -6])

res = linprog(c, A_ub=A, b_ub=b, method='simplex')
res

     con: array([], dtype=float64)
     fun: -18.4
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([0. , 0. , 0.8, 2.4])
  status: 0
 success: True
       x: array([0.8, 2.4])

In [21]:
A

array([[ 4,  2],
       [ 3,  4],
       [-1,  0],
       [ 0, -1]])

# Simulation 3

In [92]:
A = np.array([[5, 4], [10, 20], [-1, 0], [0, -1]])
b = np.array([80, 200, 0, 0])
c = np.array([-180, -200])

res = linprog(c, A_ub=A, b_ub=b, method='simplex')
res 

     con: array([], dtype=float64)
     fun: -3066.6666666666665
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([ 0.        ,  0.        , 13.33333333,  3.33333333])
  status: 0
 success: True
       x: array([13.33333333,  3.33333333])

In [45]:
data = pd.read_excel('Format data.xlsx')
data = data[:7]
data

No Tanggal pembibitan Tanggal penjualan    modal  Vitamin  Pakan halus  \
0   1         2022-07-15        2022-08-28  3000000    65000       600000   
1   2         2022-07-22        2022-09-04  2250000    50000       450000   
2   3         2022-07-29        2022-09-11  3500000    75000       700000   
3   4         2022-08-05        2022-09-18  2750000    60000       550000   
4   5         2022-08-12        2022-09-25  4800000   105000       960000   
5   6         2022-08-19        2022-10-02  1500000    35000       310000   
6   7         2022-08-26        2022-10-09  2200000    45000       430000   

   Pakan 0.5 ml  Pakan 1ml  Listrik  Gaji Karyawan  harga jual  \
0        250000     230000   200000        3900000         500   
1        180000     175000   200000        3900000         500   
2        290000     270000   200000        3900000         500   
3        210000     200000   200000        3900000         500   
4        400000     380000   200000        3900000         500   
5        130000     120000   200000        3900000         500   
6        180000     165000   200000        3900000         500   

   jumlah terjual  Total penjualan  
0           50000         25000000  
1           37000         18500000  
2           58000         29000000  
3           45000         22500000  
4           80000         40000000  
5           26000         13000000  
6           36000         18000000

In [79]:
n = 7
diagonal_matrices = -np.eye(7)
A = np.append(np.array(data[['modal', 'Vitamin', 'Pakan halus', 'Pakan 0.5 ml', 'Pakan 1ml', 'Listrik', 'Gaji Karyawan']]), diagonal_matrices, axis=0)
A
# print(A)

array([[ 3.00e+06,  6.50e+04,  6.00e+05,  2.50e+05,  2.30e+05,  2.00e+05,
         3.90e+06],
       [ 2.25e+06,  5.00e+04,  4.50e+05,  1.80e+05,  1.75e+05,  2.00e+05,
         3.90e+06],
       [ 3.50e+06,  7.50e+04,  7.00e+05,  2.90e+05,  2.70e+05,  2.00e+05,
         3.90e+06],
       [ 2.75e+06,  6.00e+04,  5.50e+05,  2.10e+05,  2.00e+05,  2.00e+05,
         3.90e+06],
       [ 4.80e+06,  1.05e+05,  9.60e+05,  4.00e+05,  3.80e+05,  2.00e+05,
         3.90e+06],
       [ 1.50e+06,  3.50e+04,  3.10e+05,  1.30e+05,  1.20e+05,  2.00e+05,
         3.90e+06],
       [ 2.20e+06,  4.50e+04,  4.30e+05,  1.80e+05,  1.65e+05,  2.00e+05,
         3.90e+06],
       [-1.00e+00, -0.00e+00, -0.00e+00, -0.00e+00, -0.00e+00, -0.00e+00,
        -0.00e+00],
       [-0.00e+00, -1.00e+00, -0.00e+00, -0.00e+00, -0.00e+00, -0.00e+00,
        -0.00e+00],
       [-0.00e+00, -0.00e+00, -1.00e+00, -0.00e+00, -0.00e+00, -0.00e+00,
        -0.00e+00],
       [-0.00e+00, -0.00e+00, -0.00e+00, -1.00e+00, -0.00e+0

In [80]:
b = np.append(np.array(data[['Total penjualan']]), np.zeros(n))
b

array([25000000., 18500000., 29000000., 22500000., 40000000., 13000000.,
       18000000.,        0.,        0.,        0.,        0.,        0.,
              0.,        0.])

In [81]:
c = np.array(data.loc[0, ['modal', 'Vitamin', 'Pakan halus', 'Pakan 0.5 ml', 'Pakan 1ml', 'Listrik', 'Gaji Karyawan']]) * -1
c

array([-3000000, -65000, -600000, -250000, -230000, -200000, -3900000],
      dtype=object)

In [82]:
res = linprog(c, A_ub=A, b_ub=b, method='simplex')
res

<ipython-input-82-ecc0766e2add>:1: OptimizeWarning: The pivot operation produces a pivot value of: 4.0e-07, which is only slightly greater than the specified tolerance 1.0e-09. This may lead to issues regarding the numerical stability of the simplex method. Removing redundant constraints, changing the pivot strategy via Bland's rule or increasing the tolerance may help reduce the issue.
  res = linprog(c, A_ub=A, b_ub=b, method='simplex')


     con: array([], dtype=float64)
     fun: -24931034.482758626
 message: 'The solution is feasible, but the solver did not report that the solution was optimal. Please try a different method.'
     nit: 13
   slack: array([ 6.89655172e+04, -3.72529030e-09, -7.45058060e-09,  2.58620690e+05,
        2.24137931e+05, -3.72529030e-09,  5.17241379e+04,  0.00000000e+00,
        0.00000000e+00,  2.75862069e+01,  3.27586207e+01,  0.00000000e+00,
        0.00000000e+00,  4.86295314e-02])
  status: 4
 success: False
       x: array([ 0.        ,  0.        , 27.5862069 , 32.75862069,  0.        ,
        0.        ,  0.04862953])